let data = `
[
    {
        "img": "img/product1.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$300",
        "color": "Color: Red",
        "size": "Size: Xl",
        "quantityTitle": "Quantity: ",
        "quantity": 2,
        "cross": "img/Vector.svg",
        "idAddButton": 0
    },
    {
        "img": "img/product2.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$200",
        "color": "Color: Red",
        "size": "Size: L",
        "quantityTitle": "Quantity: ",
        "quantity": 1,
        "cross": "img/Vector.svg",
        "idAddButton": 1
    },
    {
        "img": "img/product3.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$100",
        "color": "Color: Red",
        "size": "Size: S",
        "quantityTitle": "Quantity: ",
        "quantity": 3,
        "cross": "img/Vector.svg",
        "idAddButton": 2
    },
    {
        "img": "img/product4.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$400",
        "color": "Color: Red",
        "size": "Size: M",
        "quantityTitle": "Quantity: ",
        "quantity": 4,
        "cross": "img/Vector.svg",
        "idAddButton": 3
    },
    {
        "img": "img/product5.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$150",
        "color": "Color: Red",
        "size": "Size: Xl",
        "quantityTitle": "Quantity: ",
        "quantity": 1,
        "cross": "img/Vector.svg",
        "idAddButton": 4
    },
    {
        "img": "img/product6.jpg",
        "titleProduct": "ELLERY X M'O CAPSULE",
        "description": "Known for her sculptural takes on traditional tailoring, Australian arbiter of cool Kym Ellery teams up with Moda Operandi.",
        "priceProduct": "$52.00",
        "titleAddToCart": "MANGO  PEOPLE T-SHIRT",
        "priceTitle": "Price: ",
        "price": "$250",
        "color": "Color: Red",
        "size": "Size: XXl",
        "quantityTitle": "Quantity: ",
        "quantity": 6,
        "cross": "img/Vector.svg",
        "idAddButton": 5
    }
]
`;